version: '3.8'

services:
  db:
    container_name: otrium_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    container_name: otrium_app
    build:
      context: ./etc/php
    ports:
      - '9001:9000'
    volumes:
      - ./:/var/www/
    depends_on:
      - db

  nginx:
    container_name: otrium_nginx
    image: nginx:stable-alpine
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./:/var/www/
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - db

volumes:
  mysql-data:
    driver: local