version: '3.8'

services:
  database:
    container_name: otrium_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USER}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  php:
    container_name: otrium_php
    build:
      context: ./etc/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/
    depends_on:
      - database

  nginx:
    container_name: otrium_nginx
    image: nginx:stable-alpine
    ports:
      - '8070:80'
    volumes:
      - ./:/var/www/
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
  mysql-data:
    driver: local